import { describe, it, expect } from 'vitest';
import { filterNoise } from '../../../src/parse/filter';
import type { RawEvent } from '../../../src/parse/types';

function evt(overrides: Partial<RawEvent>): RawEvent {
  return {
    uuid: 'u',
    parentUuid: null,
    timestamp: '2026-05-21T00:00:00Z',
    type: 'user',
    ...overrides,
  };
}

describe('filterNoise', () => {
  it('drops file-history-snapshot events', () => {
    const events = [evt({ type: 'file-history-snapshot', uuid: '1' })];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops attachment events', () => {
    const events = [evt({ type: 'attachment', uuid: '1' })];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops system events', () => {
    const events = [evt({ type: 'system', uuid: '1' })];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops user events with isMeta:true', () => {
    const events = [evt({ uuid: '1', isMeta: true })];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops user messages whose content is a /clear command wrapper', () => {
    const events = [
      evt({
        uuid: '1',
        message: {
          role: 'user',
          content: '<command-name>/clear</command-name>\n<command-message>clear</command-message>',
        },
      }),
    ];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops user messages whose content is local-command-caveat boilerplate', () => {
    const events = [
      evt({
        uuid: '1',
        message: {
          role: 'user',
          content:
            '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
        },
      }),
    ];
    expect(filterNoise(events)).toEqual([]);
  });

  it('drops assistant messages with empty content', () => {
    const events = [
      evt({ uuid: '1', type: 'assistant', message: { role: 'assistant', content: '' } }),
      evt({ uuid: '2', type: 'assistant', message: { role: 'assistant', content: [] } }),
    ];
    expect(filterNoise(events)).toEqual([]);
  });

  it('keeps real user messages', () => {
    const real = evt({
      uuid: '1',
      message: { role: 'user', content: 'Please help me build a thing' },
    });
    expect(filterNoise([real])).toEqual([real]);
  });

  it('keeps real assistant messages with text', () => {
    const real = evt({
      uuid: '1',
      type: 'assistant',
      message: { role: 'assistant', content: [{ type: 'text', text: 'Sure' }] },
    });
    expect(filterNoise([real])).toEqual([real]);
  });
});
